# Change these first
owner: GetUtopiaApp  # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees:
  - elilazar

sites:
  - name: API
    url: $API
    expectedStatusCodes:
      - 200
  - name: Website
    url: https://utopia-app.com

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.utopia-app.com
  # baseUrl: /your-repo-name
  logoUrl: https://utopia-app.com/images/utopia-logo_hu_8380a076a28d9f97.webp
  name: Utopia Status
  introTitle: "**Utopia** status page powered by upptime.js monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://utopia-app.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
user-agent: GetYokeApp
