owner: GetUtopiaApp  # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees:
  - elilazar

sites:
  - name: API
    url: $API
    expectedStatusCodes:
      - 200
  - name: Website
    url: https://utopia-app.com
  - name: "Web App"
    url: https://app.utopia-app.com

status-website:
  name: "Utopia Status" # Status website title
  themeUrl: https://status.utopia-app.com/utopia.css
  logoUrl: https://utopia-app.com/images/utopia-logo.png
  cname: status.utopia-app.com
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://utopia-app.com
    - title: "Manage Account"
      href: https://app.utopia-app.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
user-agent: GetUtopiaApp
